import types from "redux-types";

export default types('ic3_patient', [
  'GET_IC3_PATIENTS',
  'GET_IC3_PATIENTS_FAILED',
  'GET_IC3_PATIENT_SCREENING_DATA',
  'GET_IC3_PATIENT_SCREENING_DATA_FAILED',
  'GET_NUTRITION_HISTORY',
  'GET_NUTRITION_HISTORY_FAILED', 
  'GET_NUTRITION_HISTORY_SUCCEEDED',
]);
