name: Build and deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-publish:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-sonatype.yml@main
    secrets: inherit

  deploy-to-nenoci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-nenoci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: neno-ci
      notify_ci_dashboard: true
    secrets: inherit
